server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  #telling the server not to register himself in the service registry
    fetch-registry: false
      
logging:
  level:
    com: ERROR
